config/routes.rb
Rails.application.routes.draw do
  root to: "pages#home"

  devise_for :users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :main_categories, only: [:show, :index]
  resources :categories, only: [:show, :index]
  resources :photos
  get 'informations', to: "pages#informations", as: 'informations'
  post 'contact', to: "pages#contact", as: :contact

  get 'categories/:id/swiper_show', to: 'categories#show_swiper', as: 'show_swiper'
end

app/views/v1/pages/home.html.erb
<div class="relative h-screen bg-black"
      data-controller="swiper"
      data-swiper-autoplay="4000">
  <div class="swiper-container h-full filter brightness-75" data-swiper-target="container">
    <ul class="swiper-wrapper list-none">
      <% Photo.for_home.shuffle.each_with_index do |item| %>
        <li class="swiper-slide relative">
          <div class="bg-black top-0 left-0 right-0 bottom-0 w-full h-full">
            <%=
              custom_cl_image_tag item.image.key,
              cover: item.cover_home,
              class: "h-full w-full swiper-lazy #{"object-#{item.menu_position}" if item.cover_home}",
              height: 1440,
              'data-swiper-target' => 'images'
            %>
          </div>
        </li>
      <% end %>
    </ul>
  </div>
  <%= stimulus_link_to main_categories_path do %>
    <div class="absolute rounded-full backdrop-blur h-1/2 w-1/2 top-1/4 left-1/4
                flex flex-col justify-center z-40 opacity-70 transition-all
                hover:opacity-100 duration-300 cursor-pointer">
      <div class="flex justify-center">
        <%=
          inline_svg_pack_tag "images/logo.svg",
          class: 'h-20 md:h-40',
          data: {
            controller: 'inline-svg',
            'svg-class' => 'fill-current text-white'
          }
        %>
      </div>
      <h1 class="text-3xl md:text-6xl text-center font-extralight text-white mt-3">
        PAUL PORTIER
      </h1>
      <h6 class="text-xl md:text-2xl text-center font-thin text-white mt-1 md:mt-3">
        PHOTOGRAPHE
      </h6>
    </div>
  <% end %>
</div>