config/routes.rb
Rails.application.routes.draw do
  root to: "pages#home"

  devise_for :users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :main_categories, only: [:show, :index]
  resources :categories, only: [:show, :index]
  resources :photos
  get 'informations', to: "pages#informations", as: 'informations'
  post 'contact', to: "pages#contact", as: :contact

  get 'categories/:id/swiper_show', to: 'categories#show_swiper', as: 'show_swiper'
end

app/views/shared/_contact_form.html.erb
<div class="hidden absolute top-20 left-0 z-90 bg-white height-full-navbar-footer w-screen flex flex-col justify-center items-center"
     id="contact-modal"
     data-contact-target="modal">

  <%= simple_form_for @contact,
                      url: contact_path,
                      method: :post,
                      html: {
                        class: 'contact-modal-form',
                          data: {
                            'contact-target' => 'form',
                            action: 'submit->contact#submit' } } do |f| %>
    <span data-action="click->contact#hide" class="close-span">
      <svg xmlns="http://www.w3.org/2000/svg" x="0px" y="0px" width="100%" height="100%" viewBox="0 0 50 50">
        <path d="M 7.71875 6.28125 L 6.28125 7.71875 L 23.5625 25 L 6.28125 42.28125 L 7.71875 43.71875 L 25 26.4375 L 42.28125 43.71875 L 43.71875 42.28125 L 26.4375 25 L 43.71875 7.71875 L 42.28125 6.28125 L 25 23.5625 Z">
        </path>
      </svg>
    </span>
    <span class="recaptcha-error-notice hidden" data-contact-target="recaptchaErrorNotice">
      Erreur recaptcha
    </span>
    <%= f.input :email, label: 'Votre email',
                wrapper_html: { class: 'contact-modal-form-input-wrapper' },
                label_html: { class: 'contact-modal-form-input-label' },
                input_html: { class: 'contact-modal-form-input-input text-xs' } %>

    <%= f.input :content, as: :text, label: 'Votre message',
                wrapper_html: { class: 'contact-modal-form-input-wrapper h-36' },
                label_html: { class: 'contact-modal-form-input-label' },
                input_html: { class: 'contact-modal-form-input-input text-sm' } %>
    <%= f.submit 'Envoyer', class: 'submit-btn' %>
    <%= recaptcha_execute('contact') %>
  <% end %>
</div>

<style type="text/css">

</style>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="flex justify-between items-center bg-white relative z-50 h-20">
  <div class="container mx-auto text-center">
    <div class="flex justify-center">
      <%= link_to 'https://www.instagram.com/paul.portier/', target: '_blank' do %>
        <span class="text-2xl px-4 mx-2"><i class="fab fa-instagram"></i></span>
      <% end %>
      <span class="text-2xl px-4 mx-2 cursor-pointer" data-action="click->contact#toggle"><i class="far fa-envelope"></i></span>
    </div>
    <hr class="py-2">
    <p class="text-xs">©<%= Time.zone.today.year %> | Paul Portier</p>
  </div>
</footer>

app/views/shared/_navbar.html.erb
<nav class="flex justify-between bg-white relative z-50 h-20" data-controller="navbar">
  <div class="px-5 xl:px-12 py-6 flex w-full items-center">
    <%= stimulus_link_to url: root_path do %>
      <%=
        inline_svg_pack_tag "images/logo.svg",
        class: 'h-10 w-8',
        data: {
          controller: 'inline-svg',
          action: "click->contact#hide",
          'svg-class' => 'fill-current text-black'
        }
      %>
    <% end %>
    <ul class="hidden md:flex px-4 mx-auto font-semibold font-heading space-x-12 absolute left-2/4 transform -translate-x-2/4">
      <li data-action="click->contact#hide">
        <%= stimulus_link_to str: "Accueil", url: root_path, class: "hover:text-gray-700" %>
      </li>
      <% @main_categories.each do |main_cat| %>
        <li class="group relative" data-action="click->contact#hide">
          <%= stimulus_link_to url: main_category_path(main_cat) do %>
            <%= main_cat.title %>
          <% end %>
          <div class="group-hover:block hidden absolute pt-7 bg-white left-2/4 transform -translate-x-2/4 pb-3 min-w-">
            <% main_cat.categories.each do |cat| %>
              <%= stimulus_link_to url: category_path(cat), class: "dropdown-element", data: { action: "click->contact#hide" } do %>
                <%= cat.title %>
              <% end -%>
            <% end %>
          </div>
        </li>
      <% end %>

      <li data-action="click->contact#hide"><%= stimulus_link_to str: 'Informations', url: informations_path, class: 'hover:text-gray-200' %></li>
      <% if user_signed_in? %>
        <li data-action="click->contact#hide"><%= link_to "Admin", admin_root_path %></li>
        <li data-action="click->contact#hide"><%= link_to "Déconnexion", destroy_user_session_path, method: :delete %></li>
      <% end %>
    </ul>
    <div class="hidden lg:flex items-center space-x-5 absolute right-12">
      <span class="flex items-center text-xl hover:text-gray-700 cursor-pointer" data-action="click->contact#toggle">
        <i class="far fa-envelope"></i>
      </span>
    </div>

    <div class="md:hidden absolute transform -translate-x-full left-full h-full w-20 items-center flex justify-center cursor-pointer"
         data-action="click->navbar#togglePhoneMenu click->contact#hide">
      <div class="phone-menu-icon">
        <input class="phone-menu-checkbox" type="checkbox" data-navbar-target="togglePhoneMenuButton" />
        <div>
          <span></span>
          <span></span>
        </div>
      </div>
    </div>
    <div class="hidden height-full-navbar-footer absolute w-full left-0 bottom-0 pb-8 overflow-y-auto"
         style="transform: translateY(100%); background: rgba(255, 255, 255, 0.9);"
         data-navbar-target="phoneMenu"
         data-action="click->navbar#hidePhoneMenu">
      <ul class="text-right px-10">
        <li class="cursor-pointer text-xl mt-12 uppercase font-light tracking-widest">
          <%= stimulus_link_to str: "Accueil", url: root_path %>
        </li>
        <% @main_categories.each do |main_cat| %>
          <li class="cursor-pointer text-xl mt-12 uppercase font-light tracking-widest">
            <%= stimulus_link_to url: main_category_path(main_cat) do %>
              <%= main_cat.title %>
            <% end %>
          </li>
          <% main_cat.categories.each do |cat| %>
            <li class="category cursor-pointer font-extralight uppercase my-1 tracking-wider">
                <%= stimulus_link_to url: category_path(cat), class: "" do %>
                  <%= cat.title %>
                <% end -%>
            </li>
          <% end %>
        <% end %>
        <li class="cursor-pointer text-xl mt-12 uppercase font-light tracking-widest">
          <%= stimulus_link_to str: 'Informations', url: informations_path %>
        </li>
        <li class="cursor-pointer text-xl mt-6 uppercase font-light tracking-widest">
          <span class="" data-action="click->navbar#hidePhoneMenu click->contact#display">
            <i class="far fa-envelope"></i>
          </span>
        </li>
        <% if user_signed_in? %>
          <li class="cursor-pointer text-xl mt-12 uppercase font-light tracking-widest">
            <%= link_to "Admin", admin_root_path %>
          </li>
          <li class="cursor-pointer text-xl mt-12 uppercase font-light tracking-widest">
            <%= link_to "Déconnexion", destroy_user_session_path, method: :delete %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/shared/_photo_modal.html.erb
<div class="modal absolute top-0 left-0 bottom-0 right-0 w-screen h-screen z-60 flex flex-col justify-center hidden bg-white"
      data-modal-target="modal">
  <div class="w-full h-full relative flex flex-col justify-center">
    <div id="close-modal" data-action="click->modal#hide" title="retour">
      <!-- <i class="fas fa-times"></i> -->
      <span><br></span>
      <svg  class="h-9 w-9 m-4"
            xmlns="http://www.w3.org/2000/svg" x="0px" y="0px" width="100%" height="100%" viewBox="0 0 50 50" style=" fill:#000000;">
        <path d="M 7.71875 6.28125 L 6.28125 7.71875 L 23.5625 25 L 6.28125 42.28125 L 7.71875 43.71875 L 25 26.4375 L 42.28125 43.71875 L 43.71875 42.28125 L 26.4375 25 L 43.71875 7.71875 L 42.28125 6.28125 L 25 23.5625 Z">
        </path>
      </svg>
    </div>
    <div class="navigate-modal left hidden lg:flex" data-action="click->modal#previous">
      <i class="fas fa-angle-left"></i>
    </div>
    <div class="navigate-modal right hidden lg:flex" data-action="click->modal#next">
      <i class="fas fa-angle-right"></i>
    </div>
    <div id="close-modal-bottom" class="md:hidden" data-action="click->modal#hide">
      <i class="fas fa-times"></i>
    </div>
    <div class="h-full w-full" data-modal-target="touchSurface">
      <% photos.each_with_index do |photo, i| %>
        <div class="elements w-full h-full object-contain absolute px-4 py-12" data-modal-target="element">

          <%#= cl_image_tag photo.image.key, class: "elements w-full h-5/6 object-contain absolute", data: { 'modal-target' => 'element' } %>
          <%= cl_image_tag photo.image.key, class: "modal-image w-full h-full object-contain", data: { target: 'content'} %>
        </div>
      <% end %>
    </div>
    <div class="absolute bottom-0 h-12 w-screen z-80 hidden sm:flex flex-wrap justify-center px-2">
      <% photos.each_with_index do |photo, i| %>
        <div class="modal-illustrations relative group h-full p-0.5 mt-0.5 cursor-pointer flex flex-col justify-center"
             data-id="<%= i %>"
             data-action="click->modal#navigateTo"
             style="width: calc(100% / <%= photos.size %>);">
          <div class="absolute opacity-0 group-hover:opacity-90 transition-all hidden"
               style="left: 50%; top: 0; width: 21rem; transform: translate(-50%, calc(-100% + -0.25rem)); cursor: default !important;">
            <%= cl_image_tag photo.image.key, class: "object-cover" %>
          </div>
          <%= cl_image_tag photo.image.key, class: "w-full h-full object-cover",
                                            data: { action: "mouseover->modal#showMiniature mouseout->modal#hideMiniature" } %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_photo_modal.htmlv1.erb
<div class="absolute top-0 left-0 bottom-0 right-0 w-screen h-screen bg-white z-60 flex flex-col justify-center">
  <div class="flex justify-between">
    <div class="w-full lg:w-2/4 h-auto p-8 lg:pr-4">
      <%= cl_image_tag photo.image.key, class: 'w-full h-full object-contain' %>
    </div>
    <div class="h-full hidden lg:flex w-2/4 p-8 flex-col justify-between lg:pl-4">
      <p class="text-3xl text-end w-full text-right uppercase font-extralight">
        <%= photo.name %>
      </p>
      <p class="text-justify font-extralight">
        <%= photo.description %>
      </p>
    </div>
  </div>
</div>