config/routes.rb
Rails.application.routes.draw do
  root to: "pages#home"

  devise_for :users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :main_categories, only: [:show, :index]
  resources :categories, only: [:show, :index]
  resources :photos
  get 'informations', to: "pages#informations", as: 'informations'
  post 'contact', to: "pages#contact", as: :contact

  get 'categories/:id/swiper_show', to: 'categories#show_swiper', as: 'show_swiper'
end

app/models/category.rb
# == Schema Information
#
# Table name: categories
#
#  id               :bigint           not null, primary key
#  title            :string
#  main_category_id :bigint           not null
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#
class Category < ApplicationRecord
  include CategoriesHelper

  belongs_to :main_category
  has_many :photos, -> { order(position: :asc) }, dependent: :destroy
  has_many :photos_for_menu, -> { where( menu: true ) }, class_name: 'Photo'
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :show_swiper]

  def show
    @back_url = "/main_categories/#{@category.main_category.id}"
    @photos = photos.includes(image_attachment: :blob).reverse
  end

  def show_swiper
    @back_url = "/categories/#{@category.id}"
    @photos = photos.rotate(params[:rotate].to_i).reverse
  end

  private

  def photos
    @category.photos
  end

  def set_category
    @category = Category.find(params[:id])
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
  def show_url
    Rails.application.routes.url_helpers.send("#{self.class.to_s.underscore}_path", self)
  end

  def random_pics(n = 10)
    Photo.where("#{self.class.to_s.underscore}_id" => self).to_a.shuffle.sample(n)
  end
end

app/views/v1/categories/show.html.erb
<%= stimulus_link_to @back_url, css_classes: 'opacity-70 hover:opacity-100 transition-all duration-300' do %>
  <%=
    inline_svg_pack_tag "images/logo.svg",
    class: 'h-40 w-full',
    data: {
      controller: 'inline-svg',
      'svg-class' => 'fill-current text-white'
    }
  %>
<% end %>
<div class="min-h-screen flex flex-col justify-center">
  <div class="flex flex-wrap justify-around p-12 mx-auto">
    <% @photos.each_with_index do |photo, index| %>
      <div class="group w-3/12 relative m-4 flex flex-col justify-center">
        <%=
          cl_image_tag photo.image.key,
          height: '500',
          crop: :fill,
          alt: "image: #{photo.name}",
          class: 'w-full',
          style: 'border: solid 1px rgba(255, 255, 255, 0.2)'
        %>
        <%= stimulus_link_to show_swiper_path(rotate: index), css_classes: "absolute h-full w-full left-0 top-0 flex flex-col
                    justify-center  text-center cursor-pointer
                    opacity-0 bg-black bg-opacity-40
                    group-hover:opacity-100 transition-all" do %>
          <span class="text-white mt-2 text-xl"><%= photo&.name %></span>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/v1/categories/show_swiper.html.erb
<div class="h-screen">
  <div class="h-full" data-controller="swiper" >
    <div class="h-24 flex">
      <div class="w-2/12">
        <%#= stimulus_link_to root_path, css_classes: 'h-full flex flex-col justify-center group' do %>
          <%#=
            inline_svg_pack_tag "images/logo.svg",
            class: 'h-5/6 w-2/6',
            data: {
              controller: 'inline-svg',
              'svg-class' => 'fill-current text-white group-hover:text-gray-500 transition-all duration-300'
            }
          %>
        <%# end %>
      </div>
      <div id="lol" class="w-8/12 text-center text-white flex flex-col justify-center" data-swiper-target="name"></div>
      <div class="w-2/12 flex justify-end">
        <%= stimulus_link_to category_path(@category),
            css_classes: 'h-full w-3/6 group flex align-center justify-center items-center',
            data_swiper_target: 'closeLink' do %>
          <%=
            inline_svg_pack_tag "images/cross.svg",
            class: 'h-2/6 w-2/6',
            data: {
              controller: 'inline-svg',
              'svg-class' => 'fill-current text-white group-hover:text-gray-500 transition-all duration-300'
            }
          %>
        <% end %>
      </div>
    </div>
    <span type="span" class="swiper-button-prev swiper-buttons" data-swiper-target="buttonPrev" data-action="click->swiper#prevSlide"></span>
    <div class="swiper-container max-h-full filter brightness-75" data-swiper-target="container"  style="height: calc(100vh - 6rem);">
      <ul class="swiper-wrapper m-0 p-0 h-full list-none">
        <% @photos.each_with_index do |item| %>
          <li class="swiper-slide h-full bg-black" data-name="<%= item.name %>" >
            <%= cl_image_tag item.image.key,
                class: 'w-full h-full object-contain',
                height: 100, width: 250,
                'data-swiper-target' => 'images' %>
          </li>
        <% end %>
      </ul>
    </div>
    <span type="span" class="swiper-button-next swiper-buttons" data-swiper-target="buttonNext" data-action="click->swiper#nextSlide"></span>
  </div>
</div>